version: ‘3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    networks:
      - kafka-network

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: python consumer/consumer.py
    depends_on:
      - kafka
    networks:
      - kafka-network
    deploy:
      replicas: 3

networks:
  kafka-network:
    driver: bridge

volumes:
  kafka-data:
