version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_NAMES: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - kafka-network
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data

  flask:
    build:
      context: .
    ports:
      - "5000:5000"
    networks:
      - kafka-network

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    command: python consumer/consumer.py
    depends_on:
      - kafka
    networks:
      - kafka-network
    deploy:
      replicas: 3

networks:
  kafka-network:
    driver: bridge

volumes:
  kafka-data:
